M = {}

M.icons = {
  Array         = '',
  Boolean       = '',
  Class         = '',
  Color         = '',
  Constant      = '',
  Constructor   = '',
  Enum          = '',
  EnumMember    = 'ﱔ',
  Event         = '',
  Field         = '',
  File          = '',
  Folder        = '',
  Function      = '',
  Interface     = '',
  Key           = '',
  Keyword       = '',
  Method        = '',
  Module        = '',
  Namespace     = '',
  Null          = 'ﱤ',
  Number        = '',
  Object        = '',
  Operator      = '',
  Package       = '',
  Property      = 'ﰠ',
  Reference     = '',
  Snippet       = '',
  String        = '',
  Struct        = '',
  TypeParameter = '',
  Unit          = '塞',
  Value         = '',
  Variable      = 'α',
}

return M
