M = {}

M.icons = {
  Array         = '󰅪',
  Boolean       = '',
  Class         = '󰌗',
  Color         = '',
  Constant      = '󰏿',
  Constructor   = '',
  Enum          = '',
  EnumMember    = '󰝖',
  Event         = '',
  Field         = '',
  File          = '',
  Folder        = '',
  Function      = '󰊕',
  Interface     = '',
  Key           = '',
  Keyword       = '',
  Method        = '',
  Module        = '󰏗',
  Namespace     = '󰋃',
  Null          = '󰟢',
  Number        = '󰎠',
  Object        = '',
  Operator      = '',
  Package       = '󰏖',
  Property      = '󰜢',
  Reference     = '󰈇',
  Snippet       = '',
  String        = '',
  Struct        = '',
  TypeParameter = '',
  Unit          = '',
  Value         = '󰑲',
  Variable      = 'α',
}

return M
